from __future__ import annotations

NEWS_PATTERN_GROUPS = {
    "routine_politics": [
        r"\belection\b",
        r"\bcandidate\b",
        r"\bsenate\b",
        r"\bcongress\b",
        r"\bparliament\b",
        r"\bprime minister\b",
        r"\bminister\b",
        r"\bparty\b",
        r"\blegislation\b",
        r"\bdemocratic\b",
        r"\brepublican\b",
        "首相",
        "政府",
        "法案",
        "国会",
        "衆院",
        "参院",
        "与党",
        "野党",
        "政局",
        "議会",
        r"\bgoverno\b",
        r"\bpresidente\b",
        r"\bcâmara\b",
        r"\bsenado\b",
        r"\bcongresso\b",
        r"\belei",
        r"\blula\b",
    ],
    "routine_sports": [
        r"\bworld cup\b",
        r"\brecap\b",
        r"\blineup\b",
        r"\bseason\b",
        r"\bleague\b",
        r"\btournament\b",
        r"\bbaseball\b",
        r"\bsoccer\b",
        r"\bfootball\b",
        r"\bbasketball\b",
        r"\bnba\b",
        r"\bmlb\b",
        r"\bnfl\b",
        r"\bnhl\b",
        "野球",
        "サッカー",
        "バスケ",
        "ラグビー",
        "試合",
        "代表",
        "ドジャース",
        "大会",
        "ホームラン",
        r"\bfutebol\b",
        r"\bcopa\b",
        r"\bjogo\b",
        r"\brodada\b",
        r"\beliminatórias\b",
    ],
    "milestone_signal": [
        r"\brecord\b",
        r"\brookie\b",
        r"\bhistoric\b",
        r"\bmilestone\b",
        r"\bfirst\b",
        r"\b300\b",
        r"\b20th\b",
        "記録",
        "史上",
        "初",
        "快挙",
        "節目",
        "新人",
        "大谷",
        "300号",
        r"\brecorde\b",
        r"\bhistóric",
        r"\bmarca\b",
        r"\bestreante\b",
    ],
    "generic_crime_or_disaster": [
        r"\barrest",
        r"\bpolice\b",
        r"\bkilled\b",
        r"\bmurder\b",
        r"\bshooting\b",
        r"\bassault\b",
        r"\bcrash\b",
        r"\bdies?\b",
        "逮捕",
        "殺害",
        "死亡",
        "事件",
        "遺体",
        "事故",
        r"\bpolícia\b",
        r"\bmorto",
        r"\bassassin",
        r"\bacidente\b",
        r"\bqueda\b",
    ],
    "recurring_story": [
        r"\bjuly 4\b",
        r"\bfourth of july\b",
        r"\bannual\b",
        r"\bholiday weekend\b",
        r"\bsummer league\b",
        r"\bopening day\b",
        "開幕",
        "合宿",
        "大会登録",
        "高校野球",
    ],
    "press_release_like": [
        r"\bpr times\b",
        r"\bembassy\b",
        r"\bfoundation\b",
        r"\bfederation\b",
        "財団",
        "協会",
        "公式",
    ],
    "civil_liberties_signal": [
        r"\bfree speech\b",
        r"\bcensorship\b",
        r"\bsurveillance\b",
        r"\bgovernment overreach\b",
        r"\bcivil rights\b",
        r"\bsue\b",
        r"\blawsuit\b",
        r"\bemail\b",
    ],
    "culture_signal": [
        r"\badaptation\b",
        r"\bauthor\b",
        r"\bcreator\b",
        r"\bfandom\b",
        r"\bviral\b",
        r"\binternet\b",
        r"\bsocial media\b",
        r"\bbook\b",
        r"\bmovie\b",
        "映画",
        "映画化",
        "アニメ",
        "炎上",
        r"\badapta",
        r"\bviral\b",
    ],
    "daily_life_signal": [
        r"\brent\b",
        r"\bhousing\b",
        r"\bprice\b",
        r"\bprices\b",
        r"\bshortage\b",
        r"\binflation\b",
        "コメ",
        "物価",
        r"\bpreço\b",
        r"\binflação\b",
    ],
    "unusual_geopolitics": [
        r"\bmissile\b",
        r"\bsubmarine\b",
        r"\bmilitary test\b",
        "ミサイル",
        "潜水艦",
    ],
}

TREND_PATTERN_GROUPS = {
    "generic_query": [
        r"\bstock market today\b",
        r"\bscores?\b",
        r"\bschedule\b",
        r"\bweather\b",
        r"\bhoroscope\b",
        r"\bfixtures\b",
        r"\braw\b",
        "試合速報",
        "結果",
        "日程",
        r"\bplacar\b",
        r"\bresultado\b",
    ],
    "reference_page": [
        r"^main page$",
        r"^メインページ$",
        r"^página principal$",
        r"^\d{4}$",
        r"^(january|february|march|april|may|june|july|august|september|october|november|december) \d{1,2}$",
        r"^\d{1,2} de [a-zç]+$",
        r"^\d+月\d+日$",
    ],
    "routine_politics": [
        r"\btrump\b",
        r"\blula\b",
        r"\btariff",
        r"\bmilitary\b",
        r"\belection\b",
        r"\bprime minister\b",
        "首相",
        "政府",
        "法案",
    ],
    "routine_sports": NEWS_PATTERN_GROUPS["routine_sports"],
    "milestone_signal": NEWS_PATTERN_GROUPS["milestone_signal"],
    "recurring_hype": [
        r"\bsummer league\b",
        r"\bopening day\b",
        r"\bweekly\b",
        r"\bseason\b",
        r"\bepisode\b",
        r"\bday \d+\b",
        "第[0-9]+話",
        "開幕",
    ],
    "culture_signal": [
        r"\badaptation\b",
        r"\bauthor\b",
        r"\bmovie\b",
        r"\bbook\b",
        r"\bcreator\b",
        r"\bfandom\b",
        r"\binheritance\b",
        r"\bfortune\b",
        r"\bsocialite\b",
        r"\beccentric\b",
        r"\bviral\b",
        "映画",
        "小説",
        "炎上",
        "米騒動",
        "遺産",
        r"\bherança\b",
        r"\bfortuna\b",
    ],
    "generic_bio": [
        r"\bis an? (actor|actress|singer|writer|footballer|soccer player|baseball player|politician)\b",
        r"\bis a japanese (actor|actress|singer|writer|politician)\b",
        r"\bis a norwegian footballer\b",
        "は、日本の俳優",
        "は、日本の女優",
        "は、日本のタレント",
        "は、日本の歌手",
        "は、日本の小説家",
        "は、日本の俳優である",
        "は、ノルウェーのサッカー選手",
        "は、.*サッカー選手",
        "は、.*野球選手",
        r"\bé (um|uma) (ator|atriz|cantor|escritor|jogador|político)\b",
    ],
    "eventful_context": [
        r"\bdied\b",
        r"\bdeath\b",
        r"\bviral\b",
        r"\bcontrovers",
        r"\bannounc",
        r"\bscandal\b",
        r"\baffair\b",
        r"\binheritance\b",
        r"\bfortune\b",
        "死去",
        "訃報",
        "炎上",
        "騒動",
        "逮捕",
        "発表",
        "引退",
        "謝罪",
        "告白",
        "批判",
        "遺産",
        r"\bmorreu\b",
        r"\bpolêmica\b",
        r"\banunci",
        r"\bherança\b",
    ],
    "generic_tragedy": [
        r"\bshooting\b",
        r"\bkilled\b",
        r"\bdead\b",
        r"\bdies?\b",
        r"\bmurder\b",
        r"\bcrash\b",
        r"\bfatal\b",
        r"\binjured\b",
        r"\bfuneral\b",
        r"\bvictims?\b",
        "銃撃",
        "死亡",
        "事故",
        "訃報",
        "morto",
        "morreu",
        "tiroteio",
        "acidente",
        "morte",
    ],
    "reddit_boilerplate": [
        r"\bweekly\b",
        r"\bmonthly\b",
        r"\bmegathread\b",
        r"\bdaily (thread|discussion)\b",
        r"\bdiscussion thread\b",
        r"\bfree talk\b",
        r"\bsimple questions\b",
        r"\bquestions thread\b",
        r"\bdirectory\b",
        r"\bno current events\b",
        r"\bread the rules\b",
        r"\bverification\b",
        r"\bsurvey\b",
        r"\bwhat are you (playing|watching|reading|listening)\b",
        r"\brules\b",
        r"post semanal",
        r"t[óo]pico semanal",
        r"moderar uma comunidade",
        r"interesse em moderar",
        "週次",
        "定期スレ",
        "質問スレ",
        "雑談スレ",
        "初心者向け",
        "사용법",
        "설문",
        "공지",
    ],
    "hard_news_spillover": [
        r"\biran\b",
        r"\brussia\b",
        r"\bukraine\b",
        r"\bwar\b",
        r"\bmissile\b",
        r"\battacks?\b",
        r"\bstrait of hormuz\b",
        r"\bofficials say\b",
        r"\btariff\b",
        r"\binvestigation\b",
        "攻撃",
        "侵攻",
        "ミサイル",
        "関税",
        r"\bataques?\b",
        r"\bguerra\b",
        r"\btarifa\b",
        r"\binvestiga",
    ],
}

PERSON_NAME_BLOCKLIST = {
    "stock",
    "market",
    "today",
    "scores",
    "schedule",
    "openai",
    "iphone",
    "tesla",
    "weather",
    "horoscope",
    "raw",
}

NEWS_FILTER_SPECS = [
    {
        "type": "regex",
        "name": "drop_press_release_like",
        "pattern_group": "press_release_like",
        "score_delta": -4,
        "drop": True,
    },
    {
        "type": "regex",
        "name": "penalize_routine_politics",
        "pattern_group": "routine_politics",
        "score_delta": -3,
    },
    {
        "type": "regex",
        "name": "penalize_routine_sports",
        "pattern_group": "routine_sports",
        "score_delta": -4,
        "unless_group": "milestone_signal",
    },
    {
        "type": "regex",
        "name": "boost_milestone_signal",
        "pattern_group": "milestone_signal",
        "score_delta": 3,
    },
    {
        "type": "regex",
        "name": "penalize_generic_crime_or_disaster",
        "pattern_group": "generic_crime_or_disaster",
        "score_delta": -3,
    },
    {
        "type": "regex",
        "name": "penalize_recurring_story",
        "pattern_group": "recurring_story",
        "score_delta": -3,
    },
    {
        "type": "regex",
        "name": "boost_civil_liberties_signal",
        "pattern_group": "civil_liberties_signal",
        "score_delta": 4,
    },
    {
        "type": "regex",
        "name": "boost_culture_signal",
        "pattern_group": "culture_signal",
        "score_delta": 3,
    },
    {
        "type": "regex",
        "name": "boost_daily_life_signal",
        "pattern_group": "daily_life_signal",
        "score_delta": 2,
    },
    {
        "type": "regex",
        "name": "boost_unusual_geopolitics",
        "pattern_group": "unusual_geopolitics",
        "score_delta": 1,
    },
    {
        "type": "local_signal",
        "name": "boost_local_signal",
        "score_delta": 1,
    },
]

TREND_FILTER_SPECS = [
    {
        "type": "platform",
        "name": "boost_reddit_youtube_culture",
        "platforms": ["reddit", "youtube"],
        "score_delta": 5,
    },
    {
        "type": "platform",
        "name": "boost_native_culture_source",
        "platforms": ["wikipedia_pageviews"],
        "score_delta": 1,
    },
    {
        "type": "regex",
        "name": "drop_reddit_boilerplate",
        "pattern_group": "reddit_boilerplate",
        "score_delta": -6,
        "drop": True,
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "drop_generic_query",
        "pattern_group": "generic_query",
        "score_delta": -5,
        "drop": True,
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "drop_reference_page",
        "pattern_group": "reference_page",
        "score_delta": -5,
        "drop": True,
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "penalize_routine_politics",
        "pattern_group": "routine_politics",
        "score_delta": -3,
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "penalize_routine_sports",
        "pattern_group": "routine_sports",
        "score_delta": -4,
        "unless_group": "milestone_signal",
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "boost_milestone_signal",
        "pattern_group": "milestone_signal",
        "score_delta": 3,
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "penalize_recurring_hype",
        "pattern_group": "recurring_hype",
        "score_delta": -3,
        "text_scope": "title",
    },
    {
        "type": "regex",
        "name": "boost_culture_signal",
        "pattern_group": "culture_signal",
        "score_delta": 4,
    },
    {
        "type": "regex",
        "name": "penalize_generic_tragedy",
        "pattern_group": "generic_tragedy",
        "score_delta": -4,
        "text_scope": "context",
    },
    {
        "type": "regex",
        "name": "penalize_hard_news_spillover",
        "pattern_group": "hard_news_spillover",
        "score_delta": -2,
        "text_scope": "context",
    },
    {
        "type": "regex",
        "name": "penalize_generic_bio_context",
        "pattern_group": "generic_bio",
        "unless_group": "eventful_context",
        "score_delta": -3,
        "text_scope": "context",
    },
    {
        "type": "bare_person_name",
        "name": "penalize_bare_person_name_title",
        "score_delta": -2,
    },
    {
        "type": "thin_context",
        "name": "penalize_thin_context",
        "score_delta": -2,
    },
    {
        "type": "local_signal",
        "name": "boost_local_signal",
        "score_delta": 1,
    },
    {
        "type": "strong_traffic",
        "name": "boost_strong_traffic",
        "threshold": 5000,
        "score_delta": 1,
    },
]
